### ISSUE TITLE
Ubuntu/CentOS compilation

### ISSUE THREAD

**Issue by andresgr** [CenacleResearch/deepstream-cpp-client#1]
Hi all,

Have anyone compiled the project for Ubuntu/CentOS? Many compilation errors appear. Here you are the log. Thanks in advance.

[deepstream-cpp-client_error.txt](https://github.com/CenacleResearch/deepstream-cpp-client/files/582833/deepstream-cpp-client_error.txt)

**Comment by KrishnaPG** [comment]
@andresgr it is still WIP (work-in-progress). Not ready for building on linux variants.

**Comment by andresgr** [comment]
Thanks a lot, I'll look forward for updates. Closing issue.
